server:
  port: 8080
  context-path: /xiaoyezhu
#  error:
#    path: /error.html
  tomcat:
    uri-encoding: utf-8
      
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 1195811561
  #druid连接池
  druid:
    initialSize: 5                                 
    minIdle: 5                                     
    maxActive: 20                                  
    maxWait: 60000                                 
    timeBetweenEvictionRunsMillis: 60000           
    minEvictableIdleTimeMillis: 300000             
    validationQuery: SELECT 1 FROM DUAL            
    testWhileIdle: true                            
    testOnBorrow: false                            
    testOnReturn: false                            
    poolPreparedStatements: false                  
    maxPoolPreparedStatementPerConnectionSize: 20  
    filters: stat,wall,log4j                       
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
  #Freemarker
  #设置ftl文件路径
#  freemarker:
#    temlate-loader-path: classpath:/templates
#    #关闭缓存，即时刷新
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attributes: request
#    suffix: .ftl
  #Thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    suffix: .html
    
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity


  
  